// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: co2box_ui1

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_splash_screen_init();
    ui_scrload_screen_init();
    ui_home_screen_init();
    ui_mainmenu_screen_init();
    ui_dmxmenu_screen_init();
    ui_MSG_screen_init();
    ui_info_screen_init();
    ui_co2menu_screen_init();
    ui_valueset_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_splash);
}

void ui_destroy(void)
{
    ui_splash_screen_destroy();
    ui_scrload_screen_destroy();
    ui_home_screen_destroy();
    ui_mainmenu_screen_destroy();
    ui_dmxmenu_screen_destroy();
    ui_MSG_screen_destroy();
    ui_info_screen_destroy();
    ui_co2menu_screen_destroy();
    ui_valueset_screen_destroy();
}
