// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: co2box_ui1

#ifndef _CO2BOX_UI1_UI_H
#define _CO2BOX_UI1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////

#include "ui_splash.h"
#include "ui_scrload.h"
#include "ui_home.h"
#include "ui_mainmenu.h"
#include "ui_dmxmenu.h"
#include "ui_MSG.h"
#include "ui_info.h"
#include "ui_co2menu.h"
#include "ui_valueset.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_bskklein_png);    // assets/bskklein.png
LV_IMG_DECLARE(ui_img_fog_png);    // assets/fog.png
LV_IMG_DECLARE(ui_img_dmxicon_en_png);    // assets/DMXICON_en.png
LV_IMG_DECLARE(ui_img_1748321345);    // assets/ETHICON-di.png
LV_IMG_DECLARE(ui_img_95950_png);    // assets/95950.png
LV_IMG_DECLARE(ui_img_dmxicon_di_png);    // assets/DMXICON_di.png
LV_IMG_DECLARE(ui_img_1667256483);    // assets/ETHICON-en.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
