// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: squareline_infobeamer_ui1

#include "ui.h"

lv_obj_t * ui_co2menu = NULL;
lv_obj_t * ui_rollerco2settings = NULL;
// event funtions

// build funtions

void ui_co2menu_screen_init(void)
{
    ui_co2menu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_co2menu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_co2menu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_co2menu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rollerco2settings = lv_roller_create(ui_co2menu);
    lv_roller_set_options(ui_rollerco2settings, "Audio Delay (ms)\nReset  (Hold)\n< Exit", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_rollerco2settings, 304);
    lv_obj_set_height(ui_rollerco2settings, 152);
    lv_obj_set_x(ui_rollerco2settings, 0);
    lv_obj_set_y(ui_rollerco2settings, 11);
    lv_obj_add_state(ui_rollerco2settings, LV_STATE_EDITED);       /// States
    lv_obj_add_flag(ui_rollerco2settings, LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags
    lv_obj_set_style_text_color(ui_rollerco2settings, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollerco2settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_rollerco2settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_rollerco2settings, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerco2settings, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_rollerco2settings, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_bskgrey);
    ui_object_set_themeable_style_property(ui_rollerco2settings, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_bskgrey);
    lv_obj_set_style_border_width(ui_rollerco2settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_rollerco2settings, 0, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_outline_pad(ui_rollerco2settings, 0, LV_PART_MAIN | LV_STATE_EDITED);

    lv_obj_set_style_text_color(ui_rollerco2settings, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollerco2settings, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerco2settings, &lv_font_montserrat_22, LV_PART_SELECTED | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_rollerco2settings, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_bskorange);
    ui_object_set_themeable_style_property(ui_rollerco2settings, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_bskorange);

}

void ui_co2menu_screen_destroy(void)
{
    if(ui_co2menu) lv_obj_del(ui_co2menu);

    // NULL screen variables
    ui_co2menu = NULL;
    ui_rollerco2settings = NULL;

}
