// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: squareline_infobeamer_ui1

#ifndef UI_CO2MENU_H
#define UI_CO2MENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_co2menu
extern void ui_co2menu_screen_init(void);
extern void ui_co2menu_screen_destroy(void);
extern lv_obj_t * ui_co2menu;
extern lv_obj_t * ui_rollerco2settings;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

