// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: co2box_ui1

#ifndef UI_DMXMENU_H
#define UI_DMXMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_dmxmenu
extern void ui_dmxmenu_screen_init(void);
extern void ui_dmxmenu_screen_destroy(void);
extern lv_obj_t * ui_dmxmenu;
extern lv_obj_t * ui_rollerdmxmenu;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

