// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: co2box_ui1

#include "ui.h"

lv_obj_t * ui_dmxmenu = NULL;
lv_obj_t * ui_rollerdmxmenu = NULL;
// event funtions

// build funtions

void ui_dmxmenu_screen_init(void)
{
    ui_dmxmenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_dmxmenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rollerdmxmenu = lv_roller_create(ui_dmxmenu);
    lv_roller_set_options(ui_rollerdmxmenu, "DMX Safety Channel\nDMX Fire Channel\n< Exit", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_rollerdmxmenu, 304);
    lv_obj_set_height(ui_rollerdmxmenu, 152);
    lv_obj_set_x(ui_rollerdmxmenu, 0);
    lv_obj_set_y(ui_rollerdmxmenu, 11);
    lv_obj_add_state(ui_rollerdmxmenu, LV_STATE_EDITED);       /// States
    lv_obj_add_flag(ui_rollerdmxmenu, LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags
    lv_obj_set_style_text_color(ui_rollerdmxmenu, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollerdmxmenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_rollerdmxmenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_rollerdmxmenu, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerdmxmenu, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_rollerdmxmenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_rollerdmxmenu, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_bskgrey);
    ui_object_set_themeable_style_property(ui_rollerdmxmenu, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_bskgrey);
    lv_obj_set_style_border_width(ui_rollerdmxmenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_rollerdmxmenu, 0, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_outline_pad(ui_rollerdmxmenu, 0, LV_PART_MAIN | LV_STATE_EDITED);

    lv_obj_set_style_text_color(ui_rollerdmxmenu, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollerdmxmenu, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerdmxmenu, &lv_font_montserrat_22, LV_PART_SELECTED | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_rollerdmxmenu, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_bskorange);
    ui_object_set_themeable_style_property(ui_rollerdmxmenu, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_bskorange);

}

void ui_dmxmenu_screen_destroy(void)
{
    if(ui_dmxmenu) lv_obj_del(ui_dmxmenu);

    // NULL screen variables
    ui_dmxmenu = NULL;
    ui_rollerdmxmenu = NULL;

}
