// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: co2box_ui1

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_home
extern void ui_home_screen_init(void);
extern void ui_home_screen_destroy(void);
extern lv_obj_t * ui_home;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_imgdmx;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_imgeth;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_lbco2saved;
extern lv_obj_t * ui_lbdmxfire;
extern lv_obj_t * ui_confire;
extern lv_obj_t * ui_lbfireadr;
extern lv_obj_t * ui_consafe;
extern lv_obj_t * ui_lbsafeadr;
extern lv_obj_t * ui_lbdmxsafe;
// CUSTOM VARIABLES
extern lv_obj_t * uic_home;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

