// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: co2box_ui1

#include "ui.h"

lv_obj_t * uic_home;
lv_obj_t * ui_home = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_imgdmx = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_imgeth = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_lbco2saved = NULL;
lv_obj_t * ui_lbdmxfire = NULL;
lv_obj_t * ui_confire = NULL;
lv_obj_t * ui_lbfireadr = NULL;
lv_obj_t * ui_consafe = NULL;
lv_obj_t * ui_lbsafeadr = NULL;
lv_obj_t * ui_lbdmxsafe = NULL;
// event funtions

// build funtions

void ui_home_screen_init(void)
{
    ui_home = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_home, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_home);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 304);
    lv_obj_set_height(ui_Container1, 49);
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, 5);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Container1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_bskgrey);
    ui_object_set_themeable_style_property(ui_Container1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_bskgrey);

    ui_imgdmx = lv_img_create(ui_Container1);
    lv_img_set_src(ui_imgdmx, &ui_img_dmxicon_en_png);
    lv_obj_set_width(ui_imgdmx, 30);
    lv_obj_set_height(ui_imgdmx, 30);
    lv_obj_set_x(ui_imgdmx, 125);
    lv_obj_set_y(ui_imgdmx, 0);
    lv_obj_set_align(ui_imgdmx, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgdmx, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgdmx, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -97);
    lv_obj_set_y(ui_Label3, 0);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "FOG SFX\nECOBLAST+");

    ui_imgeth = lv_img_create(ui_Container1);
    lv_img_set_src(ui_imgeth, &ui_img_1748321345);
    lv_obj_set_width(ui_imgeth, 30);
    lv_obj_set_height(ui_imgeth, 30);
    lv_obj_set_x(ui_imgeth, 86);
    lv_obj_set_y(ui_imgeth, 0);
    lv_obj_set_align(ui_imgeth, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgeth, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgeth, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container2 = lv_obj_create(ui_home);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 306);
    lv_obj_set_height(ui_Container2, 113);
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, 21);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Container2);
    lv_img_set_src(ui_Image2, &ui_img_95950_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, 94);
    lv_obj_set_y(ui_Image2, -8);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbco2saved = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_lbco2saved, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbco2saved, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbco2saved, 95);
    lv_obj_set_y(ui_lbco2saved, 35);
    lv_obj_set_align(ui_lbco2saved, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbco2saved, "000000 kg");
    lv_obj_set_style_text_color(ui_lbco2saved, lv_color_hex(0x2A7E00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbco2saved, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbco2saved, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbdmxfire = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_lbdmxfire, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbdmxfire, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbdmxfire, -111);
    lv_obj_set_y(ui_lbdmxfire, 19);
    lv_obj_set_align(ui_lbdmxfire, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbdmxfire, "FIRE:");
    lv_obj_set_style_text_font(ui_lbdmxfire, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_confire = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_confire);
    lv_obj_set_width(ui_confire, 86);
    lv_obj_set_height(ui_confire, 24);
    lv_obj_set_x(ui_confire, -25);
    lv_obj_set_y(ui_confire, 19);
    lv_obj_set_align(ui_confire, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_confire, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_confire, lv_color_hex(0xC80000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_confire, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_confire, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_bskorange);
    ui_object_set_themeable_style_property(ui_confire, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_bskorange);
    lv_obj_set_style_border_width(ui_confire, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbfireadr = lv_label_create(ui_confire);
    lv_obj_set_width(ui_lbfireadr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbfireadr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbfireadr, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbfireadr, "0000");
    lv_obj_set_style_text_color(ui_lbfireadr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbfireadr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_consafe = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_consafe);
    lv_obj_set_width(ui_consafe, 86);
    lv_obj_set_height(ui_consafe, 24);
    lv_obj_set_x(ui_consafe, -25);
    lv_obj_set_y(ui_consafe, -18);
    lv_obj_set_align(ui_consafe, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_consafe, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_consafe, lv_color_hex(0xFFD900), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_consafe, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_consafe, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_bskorange);
    ui_object_set_themeable_style_property(ui_consafe, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_bskorange);
    lv_obj_set_style_border_width(ui_consafe, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbsafeadr = lv_label_create(ui_consafe);
    lv_obj_set_width(ui_lbsafeadr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbsafeadr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbsafeadr, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbsafeadr, "0000");
    lv_obj_set_style_text_color(ui_lbsafeadr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbsafeadr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbdmxsafe = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_lbdmxsafe, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbdmxsafe, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbdmxsafe, -113);
    lv_obj_set_y(ui_lbdmxsafe, -18);
    lv_obj_set_align(ui_lbdmxsafe, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbdmxsafe, "SAFE:");
    lv_obj_set_style_text_font(ui_lbdmxsafe, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_home = ui_home;

}

void ui_home_screen_destroy(void)
{
    if(ui_home) lv_obj_del(ui_home);

    // NULL screen variables
    uic_home = NULL;
    ui_home = NULL;
    ui_Container1 = NULL;
    ui_imgdmx = NULL;
    ui_Label3 = NULL;
    ui_imgeth = NULL;
    ui_Container2 = NULL;
    ui_Image2 = NULL;
    ui_lbco2saved = NULL;
    ui_lbdmxfire = NULL;
    ui_confire = NULL;
    ui_lbfireadr = NULL;
    ui_consafe = NULL;
    ui_lbsafeadr = NULL;
    ui_lbdmxsafe = NULL;

}
