// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: squareline_infobeamer_ui1

#include "ui.h"

lv_obj_t * ui_info = NULL;
lv_obj_t * ui_rollerinfo = NULL;
// event funtions

// build funtions

void ui_info_screen_init(void)
{
    ui_info = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_info, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_info, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_info, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rollerinfo = lv_roller_create(ui_info);
    lv_roller_set_options(ui_rollerinfo,
                          "SERIAL: BSKWB000001\nCore-SW 1.0.1\nCore-HW BSK00150-1\nUI-HW: BSK00147-1\nUI-SW: v1.0.3\nLAN-MAC: XXXXXXXXXX\nAudioCore SW\nAudioCore HW\n< Exit",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_rollerinfo, 296);
    lv_obj_set_height(ui_rollerinfo, 152);
    lv_obj_set_x(ui_rollerinfo, -6);
    lv_obj_set_y(ui_rollerinfo, 11);
    lv_obj_set_align(ui_rollerinfo, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_rollerinfo, LV_STATE_EDITED);       /// States
    lv_obj_add_flag(ui_rollerinfo, LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags
    lv_obj_set_style_text_color(ui_rollerinfo, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollerinfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_rollerinfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_rollerinfo, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_rollerinfo, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerinfo, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_rollerinfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_rollerinfo, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_bskgrey);
    ui_object_set_themeable_style_property(ui_rollerinfo, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_bskgrey);
    lv_obj_set_style_border_width(ui_rollerinfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_rollerinfo, 0, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_outline_pad(ui_rollerinfo, 0, LV_PART_MAIN | LV_STATE_EDITED);

    lv_obj_set_style_text_color(ui_rollerinfo, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollerinfo, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_rollerinfo, LV_TEXT_ALIGN_AUTO, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerinfo, &lv_font_montserrat_22, LV_PART_SELECTED | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_rollerinfo, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_bskorange);
    ui_object_set_themeable_style_property(ui_rollerinfo, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_bskorange);

}

void ui_info_screen_destroy(void)
{
    if(ui_info) lv_obj_del(ui_info);

    // NULL screen variables
    ui_info = NULL;
    ui_rollerinfo = NULL;

}
