// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: co2box_ui1

#ifndef UI_INFO_H
#define UI_INFO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_info
extern void ui_info_screen_init(void);
extern void ui_info_screen_destroy(void);
extern lv_obj_t * ui_info;
extern lv_obj_t * ui_rollerinfo;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

