// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: co2box_ui1

#ifndef UI_MAINMENU_H
#define UI_MAINMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_mainmenu
extern void ui_mainmenu_screen_init(void);
extern void ui_mainmenu_screen_destroy(void);
extern lv_obj_t * ui_mainmenu;
extern lv_obj_t * ui_rollermainmenu;
// CUSTOM VARIABLES
extern lv_obj_t * uic_mainmenu;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

