// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: co2box_ui1

#include "ui.h"

lv_obj_t * uic_mainmenu;
lv_obj_t * ui_mainmenu = NULL;
lv_obj_t * ui_rollermainmenu = NULL;
// event funtions

// build funtions

void ui_mainmenu_screen_init(void)
{
    ui_mainmenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_mainmenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rollermainmenu = lv_roller_create(ui_mainmenu);
    lv_roller_set_options(ui_rollermainmenu,
                          "DMX Settings\nNetwork Settings\nCO2 Settings\nDevice Information\nDevice Status\nExit", LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_rollermainmenu, 4, LV_ANIM_OFF);
    lv_obj_set_width(ui_rollermainmenu, 304);
    lv_obj_set_height(ui_rollermainmenu, 152);
    lv_obj_set_x(ui_rollermainmenu, 0);
    lv_obj_set_y(ui_rollermainmenu, 11);
    lv_obj_add_state(ui_rollermainmenu, LV_STATE_EDITED);       /// States
    lv_obj_add_flag(ui_rollermainmenu, LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags
    lv_obj_set_style_text_color(ui_rollermainmenu, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollermainmenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_rollermainmenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_rollermainmenu, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollermainmenu, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_rollermainmenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_rollermainmenu, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_bskgrey);
    ui_object_set_themeable_style_property(ui_rollermainmenu, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_bskgrey);
    lv_obj_set_style_border_width(ui_rollermainmenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_rollermainmenu, 0, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_outline_pad(ui_rollermainmenu, 0, LV_PART_MAIN | LV_STATE_EDITED);

    lv_obj_set_style_text_color(ui_rollermainmenu, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollermainmenu, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollermainmenu, &lv_font_montserrat_22, LV_PART_SELECTED | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_rollermainmenu, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_bskorange);
    ui_object_set_themeable_style_property(ui_rollermainmenu, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_bskorange);

    uic_mainmenu = ui_mainmenu;

}

void ui_mainmenu_screen_destroy(void)
{
    if(ui_mainmenu) lv_obj_del(ui_mainmenu);

    // NULL screen variables
    uic_mainmenu = NULL;
    ui_mainmenu = NULL;
    ui_rollermainmenu = NULL;

}
