// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: co2box_ui1

#ifndef UI_MSG_H
#define UI_MSG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MSG
extern void ui_MSG_screen_init(void);
extern void ui_MSG_screen_destroy(void);
extern lv_obj_t * ui_MSG;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_msgheader;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_TextArea1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

