// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: squareline_infobeamer_ui1

#include "ui.h"

lv_obj_t * ui_MSG = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_msgheader = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_TextArea1 = NULL;
// event funtions

// build funtions

void ui_MSG_screen_init(void)
{
    ui_MSG = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MSG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container3 = lv_obj_create(ui_MSG);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_height(ui_Container3, 34);
    lv_obj_set_width(ui_Container3, lv_pct(94));
    lv_obj_set_x(ui_Container3, 0);
    lv_obj_set_y(ui_Container3, -49);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Container3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_bskgrey);
    ui_object_set_themeable_style_property(ui_Container3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_bskgrey);

    ui_msgheader = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_msgheader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_msgheader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_msgheader, 9);
    lv_obj_set_y(ui_msgheader, 12);
    lv_label_set_text(ui_msgheader, "INFO");

    ui_Container4 = lv_obj_create(ui_MSG);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_height(ui_Container4, 110);
    lv_obj_set_width(ui_Container4, lv_pct(94));
    lv_obj_set_x(ui_Container4, 0);
    lv_obj_set_y(ui_Container4, 14);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Container4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_bskgrey);
    ui_object_set_themeable_style_property(ui_Container4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_bskgrey);
    lv_obj_set_style_border_width(ui_Container4, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea1 = lv_textarea_create(ui_MSG);
    lv_obj_set_width(ui_TextArea1, 282);
    lv_obj_set_height(ui_TextArea1, 60);
    lv_obj_set_x(ui_TextArea1, 2);
    lv_obj_set_y(ui_TextArea1, 19);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea1, "INFOTEXT");
    lv_obj_set_style_bg_color(ui_TextArea1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TextArea1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_MSG_screen_destroy(void)
{
    if(ui_MSG) lv_obj_del(ui_MSG);

    // NULL screen variables
    ui_MSG = NULL;
    ui_Container3 = NULL;
    ui_msgheader = NULL;
    ui_Container4 = NULL;
    ui_TextArea1 = NULL;

}
