// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: squareline_infobeamer_ui1

#ifndef UI_SCRLOAD_H
#define UI_SCRLOAD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrload
extern void ui_scrload_screen_init(void);
extern void ui_scrload_screen_destroy(void);
extern lv_obj_t * ui_scrload;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES
extern lv_obj_t * uic_scrload;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

