// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: squareline_infobeamer_ui1

#include "ui.h"

lv_obj_t * uic_scrload;
lv_obj_t * ui_scrload = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Label5 = NULL;
// event funtions

// build funtions

void ui_scrload_screen_init(void)
{
    ui_scrload = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrload, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrload, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrload, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_scrload);
    lv_img_set_src(ui_Image5, &ui_img_bg_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 170
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image5, 450);
    lv_obj_set_style_img_recolor(ui_Image5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Image5, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_scrload);
    lv_img_set_src(ui_Image4, &ui_img_bskklein_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 110
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 110
    lv_obj_set_x(ui_Image4, 5);
    lv_obj_set_y(ui_Image4, -17);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 160);

    ui_Label5 = lv_label_create(ui_scrload);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 3);
    lv_obj_set_y(ui_Label5, 54);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "DEVICE LOCKED BY CLOUD\nBSK-NETWORKS.DE");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_scrload = ui_scrload;

}

void ui_scrload_screen_destroy(void)
{
    if(ui_scrload) lv_obj_del(ui_scrload);

    // NULL screen variables
    uic_scrload = NULL;
    ui_scrload = NULL;
    ui_Image5 = NULL;
    ui_Image4 = NULL;
    ui_Label5 = NULL;

}
