// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: co2box_ui1

#ifndef UI_SCRLOAD_H
#define UI_SCRLOAD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrload
extern void ui_scrload_screen_init(void);
extern void ui_scrload_screen_destroy(void);
extern lv_obj_t * ui_scrload;
extern lv_obj_t * ui_lbstart;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Spinner1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_scrload;
extern lv_obj_t * uic_lbstart;
extern lv_obj_t * uic_Spinner1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

