// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: co2box_ui1

#include "ui.h"

lv_obj_t * uic_Spinner1;
lv_obj_t * uic_lbstart;
lv_obj_t * uic_scrload;
lv_obj_t * ui_scrload = NULL;
lv_obj_t * ui_lbstart = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Spinner1 = NULL;
// event funtions

// build funtions

void ui_scrload_screen_init(void)
{
    ui_scrload = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrload, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrload, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrload, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbstart = lv_label_create(ui_scrload);
    lv_obj_set_width(ui_lbstart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbstart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbstart, -5);
    lv_obj_set_y(ui_lbstart, 55);
    lv_obj_set_align(ui_lbstart, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbstart, "starting....");

    ui_Image1 = lv_img_create(ui_scrload);
    lv_img_set_src(ui_Image1, &ui_img_fog_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 17);
    lv_obj_set_y(ui_Image1, 11);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinner1 = lv_spinner_create(ui_scrload, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 54);
    lv_obj_set_height(ui_Spinner1, 54);
    lv_obj_set_x(ui_Spinner1, 141);
    lv_obj_set_y(ui_Spinner1, 77);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner1, 11, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0x877852), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner1, 11, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Spinner1, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    uic_scrload = ui_scrload;
    uic_lbstart = ui_lbstart;
    uic_Spinner1 = ui_Spinner1;

}

void ui_scrload_screen_destroy(void)
{
    if(ui_scrload) lv_obj_del(ui_scrload);

    // NULL screen variables
    uic_scrload = NULL;
    ui_scrload = NULL;
    uic_lbstart = NULL;
    ui_lbstart = NULL;
    ui_Image1 = NULL;
    uic_Spinner1 = NULL;
    ui_Spinner1 = NULL;

}
