// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: squareline_infobeamer_ui1

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_bskorange[1] = {0xFF3B00};
const ui_theme_variable_t _ui_theme_alpha_bskorange[1] = {255};

const ui_theme_variable_t _ui_theme_color_bskgrey[1] = {0x000000};
const ui_theme_variable_t _ui_theme_alpha_bskgrey[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

