// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: squareline_infobeamer_ui1

#ifndef UI_VALUESET_H
#define UI_VALUESET_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_valueset
extern void ui_valueset_screen_init(void);
extern void ui_valueset_screen_destroy(void);
extern lv_obj_t * ui_valueset;
extern lv_obj_t * ui_lbadrsetheader1;
extern lv_obj_t * ui_Spinbox1;
extern lv_obj_t * ui_lbadrsetheader2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

