// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: squareline_infobeamer_ui1

#include "ui.h"

lv_obj_t * ui_valueset = NULL;
lv_obj_t * ui_lbadrsetheader1 = NULL;
lv_obj_t * ui_Spinbox1 = NULL;
lv_obj_t * ui_lbadrsetheader2 = NULL;
// event funtions

// build funtions

void ui_valueset_screen_init(void)
{
    ui_valueset = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_valueset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_valueset, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_valueset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbadrsetheader1 = lv_label_create(ui_valueset);
    lv_obj_set_width(ui_lbadrsetheader1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbadrsetheader1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbadrsetheader1, 34);
    lv_obj_set_y(ui_lbadrsetheader1, 26);
    lv_label_set_text(ui_lbadrsetheader1, "SET VALUE:");
    lv_obj_set_style_text_align(ui_lbadrsetheader1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbadrsetheader1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinbox1 = lv_spinbox_create(ui_valueset);
    lv_obj_set_width(ui_Spinbox1, 252);
    lv_obj_set_height(ui_Spinbox1, 67);
    lv_obj_set_x(ui_Spinbox1, -1);
    lv_obj_set_y(ui_Spinbox1, 5);
    lv_obj_set_align(ui_Spinbox1, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_Spinbox1, 4, 2);
    lv_spinbox_set_range(ui_Spinbox1, 0, 9999);
    lv_spinbox_set_cursor_pos(ui_Spinbox1, 1 - 1);
    lv_spinbox_set_value(ui_Spinbox1, 1337);
    lv_obj_set_style_radius(ui_Spinbox1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Spinbox1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Spinbox1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Spinbox1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Spinbox1, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_Spinbox1, LV_PART_CURSOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_bskorange);
    ui_object_set_themeable_style_property(ui_Spinbox1, LV_PART_CURSOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_bskorange);
    lv_obj_set_style_text_color(ui_Spinbox1, lv_color_hex(0x000000), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Spinbox1, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_lbadrsetheader2 = lv_label_create(ui_valueset);
    lv_obj_set_width(ui_lbadrsetheader2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbadrsetheader2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbadrsetheader2, 35);
    lv_obj_set_y(ui_lbadrsetheader2, 129);
    lv_label_set_text(ui_lbadrsetheader2, "HOLD TO CONFIRM");
    lv_obj_set_style_text_color(ui_lbadrsetheader2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbadrsetheader2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbadrsetheader2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbadrsetheader2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_valueset_screen_destroy(void)
{
    if(ui_valueset) lv_obj_del(ui_valueset);

    // NULL screen variables
    ui_valueset = NULL;
    ui_lbadrsetheader1 = NULL;
    ui_Spinbox1 = NULL;
    ui_lbadrsetheader2 = NULL;

}
